<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>j</string>
	</array>
	<key>name</key>
	<string>jasmin</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#class-def</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#interface-def</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#super-def</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#implements-def</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#method-def</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#field-def</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#directive</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#modifier</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#type-descriptor</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#double-string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#number</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#label</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#true-false-null</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#control</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>class-def</key>
		<dict>
			<key>begin</key>
			<string>(?=\.class)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#modifier</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#directive</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.jasmin</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([\w/]+)(?=$|\s+(?:;.*)?$)</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=^|[ 	]);.*</string>
			<key>name</key>
			<string>comment.line.jasmin</string>
		</dict>
		<key>control</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=^|\s)return(?=$|\s)</string>
			<key>name</key>
			<string>keyword.control.jasmin</string>
		</dict>
		<key>directive</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=^|\s)\.(?:catch|class|end method|field|implements|interface|limit|line|method|source|super|throws|var)(?=$|\s)</string>
			<key>name</key>
			<string>keyword.meta.directive.jasmin</string>
		</dict>
		<key>double-string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>string.begin.jasmin</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>string.end.jasmin</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.jasmin</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>string.double.jasmin</string>
				</dict>
			</array>
		</dict>
		<key>field-def</key>
		<dict>
			<key>begin</key>
			<string>(?=\.field)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#modifier</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#directive</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#double-string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type-descriptor</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.jasmin</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.type-descriptor.jasmin</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([\w/]+)\s+((?:\[+)?(?:L[/\w_]+;|[BCDFIJSZV]))(?=(\s+)?[=]|(\s+)?$|\s+;)</string>
				</dict>
			</array>
		</dict>
		<key>implements-def</key>
		<dict>
			<key>begin</key>
			<string>(?=\.implements)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.meta.directive.jasmin</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class.jasmin</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\.implements)\s+([\w/]+)</string>
				</dict>
			</array>
		</dict>
		<key>interface-def</key>
		<dict>
			<key>begin</key>
			<string>(?=\.interface)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#modifier</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#directive</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.jasmin</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([\w/]+)(?=$|\s+(?:;.*)?$)</string>
				</dict>
			</array>
		</dict>
		<key>label</key>
		<dict>
			<key>match</key>
			<string>^[^0-9][^=^:."-]*:</string>
			<key>name</key>
			<string>keyword.meta.label.jasmin</string>
		</dict>
		<key>method-def</key>
		<dict>
			<key>begin</key>
			<string>(?=\.method)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#modifier</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#directive</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type-descriptor</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.jasmin</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([\w/&lt;&gt;]+)(?=\()</string>
				</dict>
			</array>
		</dict>
		<key>modifier</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=^|\s)(?:final|static|abstract|public|friend|protected|private)(?=$|\s)</string>
			<key>name</key>
			<string>storage.modifier.jasmin</string>
		</dict>
		<key>number</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=^|[\s(,=])[-+]?(?:[1-9][0-9]*|[-+]?(?:0?\.|[1-9]\.)[0-9]+|0x[0-9A-F]+|0)(?=$|[\s,)=])</string>
			<key>name</key>
			<string>constant.numeric.jasmin</string>
		</dict>
		<key>super-def</key>
		<dict>
			<key>begin</key>
			<string>(?=\.super)</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.meta.directive.jasmin</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class.jasmin</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\.super)\s+([\w/]+)</string>
				</dict>
			</array>
		</dict>
		<key>true-false-null</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=^|[\s(,])(?:null|false|true)(?=$|[\s,)])</string>
			<key>name</key>
			<string>constant.language.jasmin</string>
		</dict>
		<key>type-descriptor</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=^|[\s()=,])(?:(?:\[+)?(?:L[/\w_]+;|[BCDFIJSZV]))(?=$|[\s,)=])</string>
			<key>name</key>
			<string>storage.type.type-descriptor.jasmin</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.jasmin</string>
	<key>uuid</key>
	<string>379c2786-2b36-4771-bece-72167eaba5c4</string>
</dict>
</plist>
